(function () {
  'use strict';

  var config = {
    version: '2026-05-05-002',
    staticCacheName: 'mesorogia-static-2026-05-05-002',
    runtimeCacheName: 'mesorogia-runtime-2026-05-05-002',
    appShell: [
      './cards.html',
      './deckmaker.html',
      './deck-post.html',
      './match-results.html',
      './favicon.ico',
      './manifest.webmanifest',
      './img/appicon_1024.webp',
      './img/appicon_192.webp',
      './img/appicon_512.webp',
      './img/tatudosi.webp',
      './css/common.css',
      './css/common-page124.css',
      './css/common-page234.css',
      './css/common-page24.css',
      './css/page1.css',
      './css/page2.css',
      './css/page3.css',
      './css/page4.css',
      './css/page5.css',
      './public/cards_latest.json',
      './public/cards_latest.meta.json',
      './public/cards_versions.json',
      './public/cv.json',
      './public/environments.json',
      './public/packs.json',
      './js/common/core/defs.js',
      './js/common/core/card-core.js',
      './js/common/core/app-helpers.js',
      './js/common/core/card-sort.js',
      './js/common/storage/owned.js',
      './js/common/storage/card-groups.js',
      './js/common/storage/deck-saved-store.js',
      './js/common/account/auth-core.js',
      './js/common/account/auth-ui.js',
      './js/common/account/account.js',
      './js/common/account/account-app-data-sync.js',
      './js/common/account/account-data-manager.js',
      './js/common/account/account-match-results.js',
      './js/common/account/header-auth.js',
      './js/common/ui/tabs.js',
      './js/common/ui/deck-saved-ui.js',
      './js/common/ui/deck-match-results-ui.js',
      './js/common/card/summary.js',
      './js/common/card/cardGrid.js',
      './js/common/card/card-detail.js',
      './js/common/card/card-image-viewer.js',
      './js/common/card/card-pick-modal.js',
      './js/common/card/cardFilter.js',
      './js/common/card/group-image-export.js',
      './js/common/filter/keyword-filter.js',
      './js/common/filter/chip-bar.js',
      './js/common/deck/deck-peek.js',
      './js/common/deck/image-export.js',
      './js/common/deck/deck-analysis.js',
      './js/common/deck/deck-note-presets.js',
      './js/common/deck/screenshot-panel.js',
      './js/common/pwa/cache-config.js',
      './js/common/pwa/install-ui.js',
      './js/common/pwa/offline-cards.js',
      './js/common/pwa/register.js',
      './js/pages/cards/cards-checker-owned-ops.js',
      './js/pages/cards/cards-checker-page.js',
      './js/pages/cards/cards-checker-render.js',
      './js/pages/cards/cards-groups-drawer-sp.js',
      './js/pages/cards/cards-groups-ui.js',
      './js/pages/cards/cards-list.js',
      './js/pages/cards/cards-page-loader.js',
      './js/pages/cards/cards-view-mode.js',
      './js/pages/deckmaker/deckmaker-campaign.js',
      './js/pages/deckmaker/deckmaker-deck.js',
      './js/pages/deckmaker/deckmaker-entry.js',
      './js/pages/deckmaker/deckmaker-filter.js',
      './js/pages/deckmaker/deckmaker-loader.js',
      './js/pages/deckmaker/deckmaker-mulligan.js',
      './js/pages/deckmaker/deckmaker-post.js',
      './js/pages/deckmaker/deckmaker-shortage-ui.js',
      './js/pages/deckmaker/deckmaker-tabs.js',
      './js/pages/deckmaker/deckmaker-ui.js',
      './js/pages/deck-post/deck-post-api.js',
      './js/pages/deck-post/deck-post-campaign.js',
      './js/pages/deck-post/deck-post-detail.js',
      './js/pages/deck-post/deck-post-editor.js',
      './js/pages/deck-post/deck-post-entry.js',
      './js/pages/deck-post/deck-post-export.js',
      './js/pages/deck-post/deck-post-filter.js',
      './js/pages/deck-post/deck-post-list.js',
      './js/pages/deck-post/deck-post-modals.js',
      './js/pages/deck-post/deck-post-page-loader.js',
      './js/pages/deck-post/deck-post-state.js',
      './js/pages/deck-post/deck-post-utils.js',
      './js/pages/match-results/match-results.js'
    ],
    offlineFallbackPage: './deckmaker.html',
    cacheFirstExtensions: [
      '.css',
      '.png',
      '.jpg',
      '.jpeg',
      '.webp',
      '.svg',
      '.ico',
      '.woff',
      '.woff2'
    ],
    networkFirstExtensions: [
      '.html',
      '.js',
      '.json'
    ]
  };

  self.MESOROGIA_PWA_CACHE_CONFIG = config;
}());
